name: Terraform VPC Deployment

on:
  workflow_dispatch:
    inputs:
      aws_account_id:
        description: 'AWS Account ID'
        required: true
        default: '339712957563'
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      vpc_name:
        description: 'Name of the VPC'
        required: true
      vpc_cidr:
        description: 'CIDR block for the VPC'
        required: true
        default: '10.94.32.0/24'
env:
  aws_account_id: ${{ github.event.inputs.aws_account_id }}
  aws_region: ${{ github.event.inputs.aws_region }}
  vpc_name: ${{ github.event.inputs.vpc_name }}
  vpc_cidr: ${{ github.event.inputs.vpc_cidr }}
  number_of_azs: ${{ github.event.inputs.number_of_azs }}
  step: ${{ github.event.inputs.step }}
  tgw_id: ${{ github.event.inputs.tgw_id }}
  ipv6_enabled: ${{ github.event.inputs.ipv6_enabled }}

jobs:
  deploy_vpc:
    runs-on: self-hosted
    name: Deploy VPC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resource creation
        if: ${{ github.event.inputs.action == 'create' }}
        run: |
          source /opt/akhil/venv/bin/activate
          mkdir temp
          cp -rf terraform/templates/vpc temp/"{{cookiecutter.generic.vpc_name}}"
          envsubst < terraform/config/vpc.yaml | yq -r > temp/cookiecutter.json
run: |
  source /opt/akhil/venv/bin/activate
  mkdir temp
  cp -rf terraform/templates/vpc temp/"{{cookiecutter.generic.vpc_name}}"
  envsubst < terraform/config/vpc.yaml | yq -r > temp/cookiecutter.json
  cd temp
  cookiecutter --output-dir terraform_output --no-input . --overwrite-if-exists

  cd terraform_output/$vpc_name
  terraform init -input=false -backend-config="backend/backend.hcl"
  terraform plan -out $vpc_name.plan
  terraform apply $vpc_name.plan

- name: Resource Destroy
  if: ${{ github.event.inputs.action == 'destroy' }}
  run: |
    source /opt/akhil/venv/bin/activate
    mkdir temp
    cp -rf terraform/templates/vpc temp/"{{cookiecutter.generic.vpc_name}}"
    envsubst < terraform/config/vpc.yaml | yq -r > temp/cookiecutter.json
    cd temp
    cookiecutter --output-dir terraform_output --no-input . --overwrite-if-exists

    cd terraform_output/$vpc_name
    terraform init -input=false -backend-config="backend/backend.hcl"
